apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: superset-data
  namespace: opendatahub
  labels:
    opendatahub.io/component: "true"
    component.opendatahub.io/name: superset
  annotations:
    volume.beta.kubernetes.io/storage-class: moc-nfs-csi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
